FROM spmallick/opencv-docker:opencv
 
COPY ./client/ /client/

COPY ./client/motion_detection_application/ /client/

COPY ./TCP/ /TCP/

COPY ./serializer/ /serializer/

COPY ./client/motion_detection_application/opencv.conf /etc/ld.so.conf.d/
 
WORKDIR /client

#RUN cmake .

#RUN make

RUN ldconfig
 
RUN g++ -std=c++11 -o client client.cpp ../TCP/clientTCP.cpp ../serializer/serializer.cpp application.cpp -I../TCP/ -I../serializer/ -pthread -I/root/installation/OpenCV-master/include/opencv4/ -L/root/installation/OpenCV-master/lib/ -lopencv_core -lopencv_imgproc -lopencv_highgui -lopencv_ml -lopencv_video -lopencv_videoio -lopencv_features2d -lopencv_calib3d -lopencv_objdetect -lopencv_flann

# not needed because the command is given from AdvantEDGE
#CMD ["./client", "10.0.2.15", "31500"]